config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, :controllers => {:registrations => "users/registrations"}

  authenticated :user do
    root to: "application#index"
  end

  root to: "tests#index"

  resources :tests, only: :index do
    resources :questions do
      resources :answers, shallow: true
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedback, only: %i[new create]

  resources :badges, only: %i[index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badge
  has_many :users, through: :users_badge
  validates :title, :image_url, :rule, :description, :value, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!

  before_action :find_user, only: %i[index]
  before_action :find_badges, only: %i[index]
  before_action :find_badge, only: %i[edit update destroy]

  def index; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule, :description, :value)
  end

  def find_user
    @user = current_user
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def find_badges
    @badges = Badge.all
  end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  before_action :find_user, only: %i[index]
  before_action :find_badges, only: %i[index]

  def index; end

  private

  def find_user
    @user = current_user
  end

  def find_badges
    @badges = Badge.all
  end

end

app/views/admin/badges/_badge.html.erb
<tr>
  <th><%= badge.title %></th>
  <th><%= badge.description %></th>
  <th><%= image_tag badge.image_url %></th>
  <td><%= link_to t('.delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('.confirmation')} %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= render 'shared/errors', resource: @badge %>
<%= form_for [:admin, @badge], :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <%= f.label :title, t('.title'), class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image_url, t('.image'), class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :image_url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, t('.description'), class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="dropdown col-md-8">
    <%=f.select :rule, [t('.first_try'), t('.category'), t('.level')], class: "btn btn-secondary dropdown-toggle col-md-1"%>
  </div>

  </div>
  <p></p>
  <div class="form-group">
    <%= f.label :value, t('.value'), class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :value, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-8"><%= f.submit t('.submit'), class: "col-md-1 btn btn-default btn-primary" %></div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= "#{t('.header')} #{@badge.title}"%></h1>
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1 class="display-4"><%= t('.header') %></h1>
<table>
  <table class = 'table'>
    <tr>
      <th scope = 'col'><%= t('.title') %></th>
      <th scope = 'col'><%= t('.description') %></th>
      <th scope = 'col'><%= t('.image') %></th>
      <th scope = 'col' colspan="1" class="text-center"><%= t('.actions') %></th>
    </tr>
    <tbody>
    <%= render @badges %>
    </tbody>
  </table>
</table>
<h3 class="text-center"><%= link_to t('.new'), new_admin_badge_path %></h3>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>
<%= render 'form' %>