config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, :controllers => {:registrations => "users/registrations"}

  authenticated :user do
    root to: "application#index"
  end

  root to: "tests#index"

  resources :tests, only: :index do
    resources :questions do
      resources :answers, shallow: true
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedback, only: %i[new create]

  resources :badges, only: %i[index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test # между тестами и вопросами
  has_many :answers # между вопросами и ответами
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  SUCCESS_RATE = 0.85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  scope :completed_tests, ->(user) { where(user_id: user.id, passed: true) }

  before_validation :before_validation_set_first_question, on: :create

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_question += 1
    end

    self.current_question = next_question
    self.passed = true if complete?
    save
  end

  def passed?
    self.correct_question / questions_size.to_f > SUCCESS_RATE
  end

  def complete?
    current_question.nil?
  end

  def questions_size
    self.test.questions.size
  end

  def question_number
    self.test.questions.index(current_question) + 1
  end

  def expired_time
    (created_at.to_i + self.test.timer * 60) - Time.now.to_i
  end

  def have_time?
    self.created_at.to_i + self.test.timer * 60 > Time.now.to_i
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update create result gist]

  def show; end

  def result; end

  def gist
    result = GistQuestionService.new(@test_passage.current_question)
    result.call
    flash_options = if result.success?
                      current_user.gists.create(question_id: @test_passage.current_question_id, link_to_gist: result.url)
                      { notice: t('.success', url: result.url) }
                    else
                      { alert: t('.fail') }
                    end
    redirect_to @test_passage, flash_options
  end

  def update
    if @test_passage.have_time?
      @test_passage.accept!(params[:answer_ids])

      if @test_passage.complete?
        BadgeService.new(@test_passage).call if @test_passage.passed?

        redirect_to result_test_passage_path(@test_passage)

      else
        render :show
      end
    else
      flash[:timer] = t('.timeout')
      redirect_to result_test_passage_path(@test_passage)
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_statistic
    correct_question_count = @test_passage.correct_question
    questions_count = @test_passage.questions_size

    return "Вы ответили на все вопросы правильно" if questions_count == correct_question_count
    return "Вы ответили на все вопросы неправильно" if correct_question_count.zero?
    "Вы ответили на #{correct_question_count} из #{questions_count} вопросов"
  end
end

app/views/test_passages/result.html.erb
<!--<h1> <%#= @test_passage.test.title %> test results </h1>-->
<%# if @test_passage.passed? %>
<!--  <h2>-->
<!--    Test passed successfully-->
<!--  </h2>-->
<!--  <h3 style = 'color: green' ><%#= result_statistic %></h3>-->
<%# else %>
<!--  <h2>-->
<!--    Test failed-->
<!--  </h2>-->
<!--  <h3 style = 'color: red' ><%#= result_statistic %></h3>-->
<%# end %>
<%#= link_to 'All Tests', tests_path %>

<nav class="navbar navbar-">
  <span class = "navbar-brand">
    <%= t('.header', name: @test_passage.test.title) %>
  </span>
</nav>
<div class="text-left p-3">
  <% if @test_passage.passed? %>
    <h3><%= t('.success') %></h3>
    <h3 style = 'color: green' ><%= result_statistic %></h3>
  <% else %>
    <h3><%= t('.fail') %></h3>
    <h3 style = 'color: red' ><%= result_statistic %></h3>
  <% end %>
  <p><%= link_to t('.tests'), tests_path, class: 'btn btn-success' %></p>
</div>

app/views/test_passages/show.html.erb
<div class="myProgress" style="width: 100%; background-color: #DDDDDD">
  <%= content_tag :div, class: "progress-bar", style: "width: 1%; height: 10px; background-color: forestgreen; text-align: center", data: {question_number: @test_passage.question_number, questions_number: @test_passage.test.questions.length } do %>
  <% end %>
</div>

<nav class="navbar navbar-light">
  <span class = "navbar-brand">
		<%= t('.header', title: @test_passage.test.title) %>
    <%= content_tag :div, '', class: 'navbar-brand timer', data: { test_timer: @test_passage.expired_time, test_passage_id: @test_passage.id } %>
  </span>
  <span class = "navbar-text">
    <%= t('.questions_count', count: @test_passage.test.questions.count) %>
    <%= t('.current_question', current: @test_passage.question_number) %>
  </span>
</nav>

<div class = 'row justify-content-left p-3'>
  <div class = "col col-md-12" >
    <h2><%= @test_passage.current_question.body %></h2>
    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <div class="form-check">
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
        <p>
          <%= b.check_box id: "anser_ids_#{b.object_id}" %>
          <%= b.label %>
        </p>
      <%end %>
        <p>
          <%= form.submit t('.next'), class: 'btn btn-success' %>
          <%= link_to t('.question'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-success' %>
        </p>
      </div>
    <% end %>
  </div>
</div>