config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, :controllers => {:registrations => "users/registrations"}

  authenticated :user do
    root to: "application#index"
  end

  root to: "tests#index"

  resources :tests, only: :index do
    resources :questions do
      resources :answers, shallow: true
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end

  resources :feedback, only: %i[new create]

  resources :badges, only: %i[index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question # между вопросами и ответами

  validates :body, presence: true
  validate :validate_number_of_question_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_number_of_question_answers
    errors.add(:question, "У вопроса не может быть больше 4 ответов") if self.question.answers.count >= 4
  end

end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[index new create]
  before_action :find_answers, only: %i[index]
  before_action :find_answer, only: %i[edit update destroy]

  def index; end

  def edit; end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_test_question_answers_path(test_id: @answer.question.test, question_id: @answer.question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_test_question_answers_path(test_id: @answer.question.test, question_id: @answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_test_question_answers_path(test_id: @answer.question.test, question_id: @answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_answers
    @answers = @question.answers
  end

  def find_question
    @question = @test.questions.find(params[:question_id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  before_action :find_test, only: %i[index]
  before_action :find_question, only: %i[index]
  before_action :find_answers, only: %i[index]

  def index; end

  private

  def find_answers
    @answers = @question.answers
  end

  def find_question
    @question = @test.questions.find(params[:question_id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
  def correct_answer(answer)
    answer.correct ? "да" : "нет"
  end
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td><%= answer.body %></td>
  <td><%= correct_answer(answer) %></td>
  <td><%= link_to 'Edit', edit_admin_answer_path(id: answer.id) %></td>
  <td><%= link_to 'Delete', admin_answer_path(id: answer.id), method: :delete, data: { confirm: "Are you sure?"} %></td>
</tr>

app/views/admin/answers/_form.html.erb
<p>
  <%= form.label :body %><br>
  <%= form.text_field :body %>
</p>
<p>
  <%= form.label :correct %><br>
  <%= form.check_box :correct %>
</p>
<p><%= form.submit %></p>

app/views/admin/answers/edit.html.erb
<h1><%= "Edit" %></h1>
<%#= link_to 'Back to question', test_question_path %>
<%= form_with model: [:admin, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct %>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/index.html.erb
<h1><%= "Answer to the question \"#{@question.body}\" on #{@test.title} test" %></h1>
<%= link_to 'New answer', new_admin_test_question_answer_path %></br>
<%= link_to 'Back to tests questons', admin_test_questions_path(params[:test_id]) %>
<table>
  <tr>
    <th>Body</th>
    <th>Correct</th>
    <th colspan="4">Actions</th>
  </tr>
  <%= render @answers %>
</table>

app/views/admin/answers/new.html.erb
<h1> Create new answer</h1>
<%= link_to 'Back to tests', admin_test_questions_path %>
<%= form_with model: [:admin, @answer.question.test, @answer.question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct %>
  </p>
  <p><%= form.submit %></p>
<% end %>